"""add suspense table

Revision ID: 488194ed29fd
Revises: 1b5ffa983b83
Create Date: 2026-05-10 16:19:41.390166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488194ed29fd'
down_revision = '1b5ffa983b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
