"""add role request fields to user

Revision ID: 77d28f3c6a59
Revises: af9661e9f1f7
Create Date: 2026-05-14 22:15:25.023038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d28f3c6a59'
down_revision = 'af9661e9f1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('role_request_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('role_request_notes', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role_request_notes')
        batch_op.drop_column('role_request_date')
        batch_op.drop_column('requested_role')

    # ### end Alembic commands ###
