"""Atualizações de novos Modelos de Contrato

Revision ID: bbc5be042f91
Revises: 1a37a1671eb6
Create Date: 2026-05-10 12:49:12.932569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc5be042f91'
down_revision = '1a37a1671eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('property_title', sa.String(length=200), nullable=False),
    sa.Column('property_address', sa.String(length=300), nullable=False),
    sa.Column('property_rent', sa.Float(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('landlord_name', sa.String(length=100), nullable=False),
    sa.Column('landlord_bi', sa.String(length=50), nullable=True),
    sa.Column('landlord_phone', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('tenant_name', sa.String(length=100), nullable=False),
    sa.Column('tenant_bi', sa.String(length=50), nullable=True),
    sa.Column('tenant_phone', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=True),
    sa.Column('security_deposit', sa.Float(), nullable=True),
    sa.Column('additional_clauses', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###
